name: Publish
on: 
  workflow_dispatch:
    inputs:
      rc: 
        type: boolean
      patch_size:
        type: choice
        description: Size Of version change
        options:
          - major
          - minor
          - patch
    

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Prepare pre-release tag
        run: |
          if [ "${{ github.event.inputs.rc }}" = "true" ]; then
            echo "Creating a release candidate pre-release tag"
            echo "PRE_TAG=rc" >> $GITHUB_ENV
          else
            echo "Creating a standard release without pre-release tag"
            echo "PRE_TAG=" >> $GITHUB_ENV
          fi

      - name: Bump version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          release_branches: ''
          pre_release_branches: '.*'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.patch_size }}
          default_prerelease_bump : ${{ github.event.inputs.patch_size }}
          tag_prefix: ""
          append_to_pre_release_tag: ${{ env.PRE_TAG }}
          dry_run: true

      - name: Display new version
        run: echo "New version is ${{ steps.tag_version.outputs.new_tag }}"

      # - name: Restore dependencies
      #   run: dotnet restore

      # - name: Build solution
      #   run: dotnet build --no-restore --configuration Release
      
      # - name: Run tests
      #   run: dotnet test --no-build --configuration Release --verbosity normal

      # - name: Publish NuGet package
      #   run: |
      #     dotnet pack DcsMissionParser.Net/DcsMissionParser.Net.csproj --no-build --configuration Release -o ./nupkg /p:PackageVersion=${{ steps.tag_version.outputs.new_tag }}
      #     dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json



     
    
  
